# Generated by Django 3.1.5 on 2021-03-08 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_auto_20210308_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bhimupi',
            name='bill_no',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cradit',
            name='bill_no',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='mobilebanking',
            name='bill_no',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='netbanking',
            name='bill_no',
            field=models.IntegerField(),
        ),
    ]
