# Generated by Django 3.1.5 on 2021-03-08 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_auto_20210308_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='netbanking',
            name='status',
            field=models.CharField(default='not paid', max_length=8),
        ),
    ]
