# Generated by Django 3.1.5 on 2021-03-09 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0012_auto_20210309_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cradit',
            name='expiry_date',
            field=models.CharField(max_length=7),
        ),
    ]
