# Generated by Django 3.1.5 on 2021-03-11 09:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Billing_System', '0003_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment_status',
            name='detail',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='payment_status',
            name='key_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='id'),
        ),
    ]
