# Generated by Django 3.1.5 on 2021-02-24 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='Phone_number',
            field=models.IntegerField(),
        ),
    ]
