# Generated by Django 3.1.5 on 2021-02-24 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0002_auto_20210224_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='Phone_number',
            field=models.IntegerField(max_length=10),
        ),
    ]
