# Generated by Django 3.1.5 on 2021-03-06 12:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0003_auto_20210224_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='Phone_number',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\d{9,15}$')]),
        ),
    ]
