# Generated by Django 3.1.5 on 2021-03-06 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0004_auto_20210306_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='meter_no',
            field=models.CharField(default=0, max_length=10, unique=True),
        ),
    ]
