# Generated by Django 3.1.5 on 2021-03-07 17:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0005_login_meter_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='Phone_number',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '999999999'. Up to 13 digits allowed.", regex='^\\d{9,13}$')]),
        ),
    ]
